import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// Clean reconstruction of translation resources without corruption
const resources = {
  en: { translation: {
    nav: { home: 'Home', rights: 'Know Your Rights', resources: 'Resources', help: 'Paperwork Help', about: 'About' },
    home: { title: 'Welcome to Immigo', subtitle: 'Your Guide to Immigrant Rights & Resources', description: 'Empowering immigrants with knowledge about their rights, legal information, and community resources.', getStarted: 'Get Started', features: { rights: { title: 'Know Your Rights', description: 'Learn about your rights as a documented or undocumented immigrant.' }, resources: { title: 'Find Resources', description: 'Access reliable legal and community resources in your area.' }, chatbot: { title: 'AI Assistant', description: 'Get answers to your immigration questions with our AI chatbot.' } } },
    rights: { title: 'Know Your Rights', subtitle: 'Understanding Your Rights as an Immigrant', section1: { title: 'Right to Remain Silent', content: 'You have the right to remain silent and not answer questions about your immigration status.' }, section2: { title: 'Right to an Attorney', content: 'You have the right to speak with an attorney before answering any questions.' }, section3: { title: 'Right to Refuse Search', content: 'You may refuse a search of your home or belongings without a warrant.' }, section4: { title: 'Right to Documentation', content: 'You can carry ID but do not have to show it unless lawfully detained.' }, disclaimer: 'Educational only – not legal advice.' },
    resources: { title: 'Resources', subtitle: 'Legal Aid & Community Resources', videoResourcesTitle: 'Video Resources', legalAid: { title: 'Legal Aid Organizations', description: 'Find free or low-cost legal assistance.', organizations: { nilc: { name: 'National Immigration Law Center', description: 'Defends and advances rights of low-income immigrants.' }, ian: { name: 'Immigration Advocates Network', description: 'Network offering free immigration legal services.' }, aila: { name: 'American Immigration Lawyers Association', description: 'Professional association of immigration attorneys.' } } }, hotlines: { title: 'Emergency Hotlines', description: '24/7 hotlines for immediate assistance.', entries: { detentionHotline: { name: 'National Immigration Detention Hotline', description: '24/7 hotline for people in detention.', phone: '1-888-373-7888' }, iceLocator: { name: 'ICE Detainee Locator', description: 'Tool & line to locate detainees.', phone: '1-855-448-6903' }, unitedWeDream: { name: 'United We Dream Hotline', description: 'Support for immigrant youth & families.', phone: '1-844-363-1423' } } }, community: { title: 'Community Organizations', description: 'Local organizations providing support.', entries: { localCenters: { name: 'Local Community Centers', description: 'Check centers for immigrant services.' }, religiousOrgs: { name: 'Religious Organizations', description: 'Many faith institutions offer support.' }, legalAidSocieties: { name: 'Legal Aid Societies', description: 'Local groups providing free/low-cost aid.' } } }, visitWebsite: 'Visit Website →', playlistComingSoon: 'Playlist coming soon in your language.', noteTitle: 'Note', noteContent: 'Verify resource details before contacting.' },
    help: { title: 'Paperwork Help', subtitle: 'Common Immigration Forms', description: 'Guidance for understanding and completing forms.', commonFormsTitle: 'Common Forms', viewFormLabel: 'View Form →', tipsTitle: 'Form Tips', tips: { tip1: 'Read instructions fully.', tip2: 'Use black ink clearly.', tip3: 'Answer truthfully.', tip4: 'Keep copies.', tip5: 'Consult a lawyer if unsure.', tip6: 'Review before submitting.' }, chatbotSectionTitle: 'Need Help? Ask the AI', chatbotSectionDescription: 'Use the chatbot for form & process questions.', disclaimerText: 'Check official USCIS sources for current info.' },
    about: { title: 'About Immigo', subtitle: 'Empowering with Information', description: 'Helping immigrants understand rights and access resources.', missionTitle: 'Our Mission', whatWeOfferTitle: 'What We Offer', features: { rightsLabel: 'Know Your Rights', resourceFinderLabel: 'Resource Finder', paperworkHelpLabel: 'Paperwork Help', aiAssistantLabel: 'AI Assistant', multilingualSupportLabel: 'Multilingual Support' }, disclaimerTitle: 'Disclaimer', contactTitle: 'Contact', disclaimerText: 'Information only – not legal advice.', contactText: 'Reach us via chatbot or local legal org.' },
    chatbot: { title: 'AI Assistant', placeholder: 'Ask a question...', send: 'Send', thinking: 'Thinking...', error: 'Error occurred – retry.', apiKeyMissing: 'Set VITE_GEMINI_API_KEY in .env.', welcomeGreeting: '👋 AI Assistant', welcomePrompt: 'Ask about rights, laws, resources.', toggleAria: 'Toggle chatbot', closeAria: 'Close chatbot', systemPrompt: 'Provide US immigration rights, laws & resources info. Not legal advice.' },
    footer: { description: 'Empowering immigrants with knowledge.', rights: 'All rights reserved.' }
  } },
  es: { translation: {
    nav: { home: 'Inicio', rights: 'Conoce Tus Derechos', resources: 'Recursos', help: 'Ayuda con Documentos', about: 'Acerca de' },
    home: { title: 'Bienvenido a Immigo', subtitle: 'Guía de Derechos y Recursos', description: 'Empoderando a inmigrantes con conocimiento y recursos.', getStarted: 'Comenzar', features: { rights: { title: 'Conoce Tus Derechos', description: 'Aprende sobre tus derechos.' }, resources: { title: 'Encuentra Recursos', description: 'Accede a recursos confiables.' }, chatbot: { title: 'Asistente IA', description: 'Obtén respuestas sobre inmigración.' } } },
    rights: { title: 'Conoce Tus Derechos', subtitle: 'Entiende tus derechos', section1: { title: 'Derecho a Guardar Silencio', content: 'Puedes guardar silencio y pedir un abogado.' }, section2: { title: 'Derecho a un Abogado', content: 'Puedes hablar con un abogado antes de responder.' }, section3: { title: 'Derecho a Negar Registro', content: 'Puedes negar un registro sin orden judicial.' }, section4: { title: 'Derecho a Documentos', content: 'Puedes portar identificación sin mostrarla salvo detención legal.' }, disclaimer: 'Solo educativo – no asesoría legal.' },
    resources: { title: 'Recursos', subtitle: 'Asistencia Legal y Comunitaria', videoResourcesTitle: 'Recursos en Video', legalAid: { title: 'Organizaciones de Asistencia Legal', description: 'Encuentra ayuda legal gratis o de bajo costo.', organizations: { nilc: { name: 'Centro Nacional de Leyes de Inmigración', description: 'Defiende derechos de inmigrantes de bajos ingresos.' }, ian: { name: 'Red de Defensores de Inmigración', description: 'Red que ofrece servicios legales gratuitos.' }, aila: { name: 'Asociación Americana de Abogados de Inmigración', description: 'Asociación profesional de abogados.' } } }, hotlines: { title: 'Líneas de Emergencia', description: 'Líneas 24/7 para asistencia inmediata.', entries: { detentionHotline: { name: 'Línea Nacional de Detención', description: 'Línea 24/7 para personas detenidas.', phone: '1-888-373-7888' }, iceLocator: { name: 'Localizador de Detenidos ICE', description: 'Herramienta para ubicar detenidos.', phone: '1-855-448-6903' }, unitedWeDream: { name: 'Línea United We Dream', description: 'Apoyo para jóvenes y familias inmigrantes.', phone: '1-844-363-1423' } } }, community: { title: 'Organizaciones Comunitarias', description: 'Organizaciones locales de apoyo.', entries: { localCenters: { name: 'Centros Comunitarios Locales', description: 'Busca servicios de apoyo.' }, religiousOrgs: { name: 'Organizaciones Religiosas', description: 'Iglesias y templos ofrecen apoyo.' }, legalAidSocieties: { name: 'Sociedades de Asistencia Legal', description: 'Grupos con servicios legales.' } } }, visitWebsite: 'Visitar Sitio →', playlistComingSoon: 'Lista pronto en tu idioma.', noteTitle: 'Nota', noteContent: 'Verifica detalles antes de contactar.' },
    help: { title: 'Ayuda con Documentos', subtitle: 'Formularios Comunes', description: 'Guía para formularios de inmigración.', commonFormsTitle: 'Formularios Comunes', viewFormLabel: 'Ver Formulario →', tipsTitle: 'Consejos', tips: { tip1: 'Lee las instrucciones.', tip2: 'Usa tinta negra clara.', tip3: 'Responde con verdad.', tip4: 'Guarda copias.', tip5: 'Consulta un abogado si dudas.', tip6: 'Revisa antes de enviar.' }, chatbotSectionTitle: '¿Necesitas ayuda? IA', chatbotSectionDescription: 'Usa el chatbot para preguntas.', disclaimerText: 'Verifica siempre fuentes oficiales.' },
    about: { title: 'Acerca de Immigo', subtitle: 'Empoderando con Información', description: 'Ayuda a inmigrantes a entender derechos.', missionTitle: 'Nuestra Misión', whatWeOfferTitle: 'Lo Que Ofrecemos', features: { rightsLabel: 'Conoce Tus Derechos', resourceFinderLabel: 'Buscador de Recursos', paperworkHelpLabel: 'Ayuda con Documentos', aiAssistantLabel: 'Asistente IA', multilingualSupportLabel: 'Soporte Multilingüe' }, disclaimerTitle: 'Aviso Legal', contactTitle: 'Contacto', disclaimerText: 'Información – no asesoría legal.', contactText: 'Escríbenos vía chatbot.' },
    chatbot: { title: 'Asistente IA', placeholder: 'Haz una pregunta...', send: 'Enviar', thinking: 'Pensando...', error: 'Error – inténtalo de nuevo.', apiKeyMissing: 'Configura VITE_GEMINI_API_KEY.', welcomeGreeting: '👋 Asistente IA', welcomePrompt: 'Pregunta sobre derechos o recursos.', toggleAria: 'Alternar chatbot', closeAria: 'Cerrar chatbot', systemPrompt: 'Ofrece información de inmigración. No asesoría legal.' },
    footer: { description: 'Empoderando inmigrantes.', rights: 'Todos los derechos reservados.' }
  } },
  fr: { translation: {
    nav: { home: 'Accueil', rights: 'Connaissez Vos Droits', resources: 'Ressources', help: 'Aide aux Documents', about: 'À Propos' },
    home: { title: 'Bienvenue sur Immigo', subtitle: 'Guide des Droits & Ressources', description: 'Autonomiser les immigrants par la connaissance.', getStarted: 'Commencer', features: { rights: { title: 'Vos Droits', description: 'Apprenez vos droits.' }, resources: { title: 'Trouver des Ressources', description: 'Accédez à des ressources fiables.' }, chatbot: { title: 'Assistant IA', description: 'Réponses à vos questions.' } } },
    rights: { title: 'Connaissez Vos Droits', subtitle: 'Comprendre vos droits', section1: { title: 'Droit au Silence', content: 'Vous pouvez garder le silence.' }, section2: { title: 'Droit à un Avocat', content: 'Consultez un avocat avant de répondre.' }, section3: { title: 'Refuser une Fouille', content: 'Refusez sans mandat.' }, section4: { title: 'Documents', content: 'Porter une pièce d’identité sans la montrer sauf détention.' }, disclaimer: 'Éducatif – pas conseil juridique.' },
    resources: { title: 'Ressources', subtitle: 'Aide Juridique & Communautaire', videoResourcesTitle: 'Ressources vidéo', legalAid: { title: 'Organisations d’aide juridique', description: 'Aide juridique gratuite ou abordable.', organizations: { nilc: { name: 'Centre National de Droit de l’Immigration', description: 'Défense des droits des immigrés.' }, ian: { name: 'Réseau des Défenseurs de l’Immigration', description: 'Services juridiques gratuits.' }, aila: { name: 'Association Américaine des Avocats d’Immigration', description: 'Association professionnelle.' } } }, hotlines: { title: 'Lignes d’urgence', description: 'Assistance 24h/24.', entries: { detentionHotline: { name: 'Hotline Détention', description: 'Ligne pour personnes détenues.', phone: '1-888-373-7888' }, iceLocator: { name: 'Localisateur ICE', description: 'Outil localiser détenus.', phone: '1-855-448-6903' }, unitedWeDream: { name: 'Hotline United We Dream', description: 'Soutien aux jeunes et familles.', phone: '1-844-363-1423' } } }, community: { title: 'Organisations communautaires', description: 'Soutien local.', entries: { localCenters: { name: 'Centres Communautaires Locaux', description: 'Consultez les centres locaux.' }, religiousOrgs: { name: 'Organisations Religieuses', description: 'Églises et mosquées offrent du soutien.' }, legalAidSocieties: { name: 'Sociétés d’Aide Juridique', description: 'Services gratuits ou abordables.' } } }, visitWebsite: 'Visiter le Site →', playlistComingSoon: 'Bientôt disponible.', noteTitle: 'Remarque', noteContent: 'Vérifiez avant de contacter.' },
    help: { title: 'Aide aux Documents', subtitle: 'Formulaires Courants', description: 'Aide pour remplir les formulaires.', commonFormsTitle: 'Formulaires Courants', viewFormLabel: 'Voir →', tipsTitle: 'Conseils', tips: { tip1: 'Lisez les instructions.', tip2: 'Encre noire lisible.', tip3: 'Réponses honnêtes.', tip4: 'Gardez des copies.', tip5: 'Consultez un avocat si doute.', tip6: 'Relisez avant envoi.' }, chatbotSectionTitle: 'Besoin d’aide ?', chatbotSectionDescription: 'Utilisez le chatbot.', disclaimerText: 'Vérifiez les sources officielles.' },
    about: { title: 'À Propos', subtitle: 'Informer et Autonomiser', description: 'Aider à comprendre les droits.', missionTitle: 'Mission', whatWeOfferTitle: 'Offre', features: { rightsLabel: 'Vos Droits', resourceFinderLabel: 'Ressources', paperworkHelpLabel: 'Aide Docs', aiAssistantLabel: 'Assistant IA', multilingualSupportLabel: 'Support Multilingue' }, disclaimerTitle: 'Avertissement', contactTitle: 'Contact', disclaimerText: 'Information – pas conseil juridique.', contactText: 'Contact via chatbot.' },
    chatbot: { title: 'Assistant IA', placeholder: 'Posez une question...', send: 'Envoyer', thinking: 'Réflexion…', error: 'Erreur – réessayez.', apiKeyMissing: 'Définir VITE_GEMINI_API_KEY.', welcomeGreeting: '👋 Assistant IA', welcomePrompt: 'Questions sur droits/ressources.', toggleAria: 'Basculer chatbot', closeAria: 'Fermer chatbot', systemPrompt: 'Fournit information immigration. Pas juridique.' },
    footer: { description: 'Autonomiser par la connaissance.', rights: 'Tous droits réservés.' }
  } },
  ar: { translation: {
    nav: { home: 'الرئيسية', rights: 'اعرف حقوقك', resources: 'الموارد', help: 'مساعدة بالأوراق', about: 'حول' },
    home: { title: 'مرحبًا بك في Immigo', subtitle: 'دليل الحقوق والموارد', description: 'تمكين المهاجرين بالمعلومات.', getStarted: 'ابدأ', features: { rights: { title: 'اعرف حقوقك', description: 'تعرّف على حقوقك.' }, resources: { title: 'ابحث عن موارد', description: 'وصول إلى موارد موثوقة.' }, chatbot: { title: 'المساعد الذكي', description: 'أجوبة على أسئلة الهجرة.' } } },
    rights: { title: 'اعرف حقوقك', subtitle: 'فهم الحقوق', section1: { title: 'حق التزام الصمت', content: 'يمكنك التزام الصمت وطلب محامٍ.' }, section2: { title: 'حق محامٍ', content: 'تحدث مع محامٍ قبل الإجابة.' }, section3: { title: 'رفض التفتيش', content: 'يمكنك رفض التفتيش دون مذكرة.' }, section4: { title: 'الوثائق', content: 'تحمل هوية دون إظهارها إلا عند الاحتجاز.' }, disclaimer: 'تعليمي فقط – ليس نصيحة قانونية.' },
    resources: { title: 'الموارد', subtitle: 'مساعدة قانونية ومجتمعية', videoResourcesTitle: 'موارد فيديو', legalAid: { title: 'منظمات المساعدة القانونية', description: 'اعثر على مساعدة قانونية مجانية أو منخفضة التكلفة.', organizations: { nilc: { name: 'المركز الوطني لقانون الهجرة', description: 'يدافع عن حقوق المهاجرين منخفضي الدخل.' }, ian: { name: 'شبكة دعاة الهجرة', description: 'شبكة تقدم خدمات قانونية مجانية.' }, aila: { name: 'جمعية المحامين الأمريكيين للهجرة', description: 'جمعية مهنية لمحامي الهجرة.' } } }, hotlines: { title: 'خطوط طوارئ', description: 'خطوط دعم فوري 24/7.', entries: { detentionHotline: { name: 'خط احتجاز الهجرة', description: 'خط ساخن للمحتجزين.', phone: '1-888-373-7888' }, iceLocator: { name: 'محدد محتجزي ICE', description: 'أداة لتحديد المحتجزين.', phone: '1-855-448-6903' }, unitedWeDream: { name: 'خط United We Dream', description: 'دعم للشباب والأسر.', phone: '1-844-363-1423' } } }, community: { title: 'منظمات مجتمعية', description: 'منظمات دعم محلية.', entries: { localCenters: { name: 'مراكز مجتمعية محلية', description: 'تحقق من خدمات الدعم.' }, religiousOrgs: { name: 'منظمات دينية', description: 'المؤسسات الدينية تقدم الدعم.' }, legalAidSocieties: { name: 'جمعيات المساعدة القانونية', description: 'خدمات مجانية أو منخفضة التكلفة.' } } }, visitWebsite: 'زيارة الموقع →', playlistComingSoon: 'القائمة قريبًا بلغتك.', noteTitle: 'ملاحظة', noteContent: 'تحقق من المعلومات قبل التواصل.' },
    help: { title: 'مساعدة بالأوراق', subtitle: 'نماذج شائعة', description: 'إرشاد لملء النماذج.', commonFormsTitle: 'نماذج شائعة', viewFormLabel: 'عرض →', tipsTitle: 'نصائح', tips: { tip1: 'اقرأ التعليمات.', tip2: 'حبر أسود واضح.', tip3: 'أجب بصدق.', tip4: 'احتفظ بنسخ.', tip5: 'استشر محامٍ عند الحاجة.', tip6: 'راجع قبل الإرسال.' }, chatbotSectionTitle: 'بحاجة لمساعدة؟', chatbotSectionDescription: 'استخدم المساعد للأسئلة.', disclaimerText: 'تحقق من المصادر الرسمية دائماً.' },
    about: { title: 'حول Immigo', subtitle: 'تمكين بالمعلومات', description: 'مساعدة المهاجرين على فهم حقوقهم.', missionTitle: 'مهمتنا', whatWeOfferTitle: 'ما نقدمه', features: { rightsLabel: 'اعرف حقوقك', resourceFinderLabel: 'بحث عن الموارد', paperworkHelpLabel: 'مساعدة بالأوراق', aiAssistantLabel: 'المساعد الذكي', multilingualSupportLabel: 'دعم متعدد اللغات' }, disclaimerTitle: 'إخلاء مسؤولية', contactTitle: 'اتصال', disclaimerText: 'معلومات فقط – ليست نصيحة قانونية.', contactText: 'تواصل عبر المساعد.' },
    chatbot: { title: 'المساعد الذكي', placeholder: 'اسأل سؤالًا...', send: 'إرسال', thinking: 'جارٍ التفكير...', error: 'حدث خطأ.', apiKeyMissing: 'ضبط VITE_GEMINI_API_KEY.', welcomeGreeting: '👋 المساعد الذكي', welcomePrompt: 'اسأل عن الحقوق أو الموارد.', toggleAria: 'تبديل المساعد', closeAria: 'إغلاق المساعد', systemPrompt: 'معلومات هجرة عامة. ليست نصيحة قانونية.' },
    footer: { description: 'تمكين المهاجرين بالمعرفة.', rights: 'جميع الحقوق محفوظة.' }
  } },
  zh: { translation: {
    nav: { home: '首页', rights: '了解权利', resources: '资源', help: '文书协助', about: '关于' },
    home: { title: '欢迎来到 Immigo', subtitle: '移民权利与资源指南', description: '通过信息赋能移民。', getStarted: '开始', features: { rights: { title: '了解您的权利', description: '了解移民的基本权利。' }, resources: { title: '查找资源', description: '获取可靠法律与社区资源。' }, chatbot: { title: '智能助手', description: '获取移民相关解答。' } } },
    rights: { title: '了解您的权利', subtitle: '理解作为移民的权利', section1: { title: '保持沉默', content: '可保持沉默并请求律师。' }, section2: { title: '律师协助', content: '回答前可与律师交谈。' }, section3: { title: '拒绝搜查', content: '无令状可拒绝搜查。' }, section4: { title: '证件权', content: '携带证件无须展示除非被合法盘查。' }, disclaimer: '仅教育用途 – 非法律建议。' },
    resources: { title: '资源', subtitle: '法律援助与社区资源', videoResourcesTitle: '视频资源', legalAid: { title: '法律援助组织', description: '寻找低成本法律援助。', organizations: { nilc: { name: '全国移民法律中心', description: '维护低收入移民权利。' }, ian: { name: '移民倡导者网络', description: '免费移民法律服务网络。' }, aila: { name: '美国移民律师协会', description: '移民律师专业协会。' } } }, hotlines: { title: '紧急热线', description: '全天热线即时支持。', entries: { detentionHotline: { name: '拘留热线', description: '为被拘留者提供支持。', phone: '1-888-373-7888' }, iceLocator: { name: 'ICE 在押查询', description: '查询被 ICE 拘留人员。', phone: '1-855-448-6903' }, unitedWeDream: { name: 'United We Dream 热线', description: '为移民青年与家庭提供支持。', phone: '1-844-363-1423' } } }, community: { title: '社区组织', description: '本地支持团体。', entries: { localCenters: { name: '社区中心', description: '查找支持服务。' }, religiousOrgs: { name: '宗教组织', description: '宗教场所常提供帮助。' }, legalAidSocieties: { name: '法律援助协会', description: '提供免费或低成本援助。' } } }, visitWebsite: '访问网站 →', playlistComingSoon: '您的语言列表即将推出。', noteTitle: '注意', noteContent: '联系前请核实信息。' },
    help: { title: '文书协助', subtitle: '常见表格', description: '填写表格的指导。', commonFormsTitle: '常见表格', viewFormLabel: '查看 →', tipsTitle: '提示', tips: { tip1: '先读说明。', tip2: '黑色墨水清晰填写。', tip3: '真实完整回答。', tip4: '保存副本。', tip5: '不确定时咨询律师。', tip6: '提交前复核。' }, chatbotSectionTitle: '需要帮助？', chatbotSectionDescription: '使用聊天助手。', disclaimerText: '请核实官方最新信息。' },
    about: { title: '关于 Immigo', subtitle: '用信息赋能', description: '帮助移民获取权利与资源。', missionTitle: '使命', whatWeOfferTitle: '提供内容', features: { rightsLabel: '了解权利', resourceFinderLabel: '资源查找', paperworkHelpLabel: '文书协助', aiAssistantLabel: '智能助手', multilingualSupportLabel: '多语言支持' }, disclaimerTitle: '免责声明', contactTitle: '联系方式', disclaimerText: '仅信息参考 – 非法律建议。', contactText: '通过助手联系我们。' },
    chatbot: { title: '智能助手', placeholder: '提问...', send: '发送', thinking: '思考中…', error: '发生错误。', apiKeyMissing: '设置 VITE_GEMINI_API_KEY。', welcomeGreeting: '👋 智能助手', welcomePrompt: '欢迎提问。', toggleAria: '切换助手', closeAria: '关闭助手', systemPrompt: '提供移民信息，不是法律建议。' },
    footer: { description: '以知识赋能移民。', rights: '保留所有权利。' }
  } },
  ht: { translation: {
    nav: { home: 'Akèy', rights: 'Konnen Dwa Ou', resources: 'Resous', help: 'Èd Papye', about: 'Konsènan' },
    home: { title: 'Byenveni nan Immigo', subtitle: 'Gid Dwa & Resous Imigran', description: 'Bay imigran enfòmasyon sou dwa ak resous.', getStarted: 'Kòmanse', features: { rights: { title: 'Konnen Dwa Ou', description: 'Aprann dwa ou.' }, resources: { title: 'Chèche Resous', description: 'Aksè a resous serye.' }, chatbot: { title: 'Asistan IA', description: 'Repons sou kesyon imigrasyon.' } } },
    rights: { title: 'Konnen Dwa Ou', subtitle: 'Konprann dwa ou', section1: { title: 'Dwa pou rete an silans', content: 'Ou ka rete an silans epi mande yon avoka.' }, section2: { title: 'Dwa Avoka', content: 'Pale ak yon avoka anvan ou reponn.' }, section3: { title: 'Refize Fouy', content: 'Ou ka refize fouy san manda.' }, section4: { title: 'Dwa Dokiman', content: 'Pote idantite san oblije montre li.' }, disclaimer: 'Edikatif sèlman – pa konsèy legal.' },
    resources: { title: 'Resous', subtitle: 'Èd Legal & Kominotè', videoResourcesTitle: 'Resous Videyo', legalAid: { title: 'Òganizasyon Èd Legal', description: 'Jwenn èd legal gratis oswa a ti pri.', organizations: { nilc: { name: 'Sant Nasyonal Dwa Imigrasyon', description: 'Defann dwa imigran ki gen revni ba.' }, ian: { name: 'Rezo Defansè Imigrasyon', description: 'Rezo sèvis legal gratis.' }, aila: { name: 'Asosyasyon Ameriken Avoka Imigrasyon', description: 'Asosyasyon pwofesyonèl avoka.' } } }, hotlines: { title: 'Liy Ijans', description: 'Liy dirèk 24/7 pou asistans.', entries: { detentionHotline: { name: 'Liy Detansyon Imigrasyon', description: 'Liy 24/7 pou moun nan detansyon.', phone: '1-888-373-7888' }, iceLocator: { name: 'Lokalizatè Detni ICE', description: 'Zouti pou jwenn yon moun nan gad ICE.', phone: '1-855-448-6903' }, unitedWeDream: { name: 'Liy United We Dream', description: 'Sipò pou jèn ak fanmi imigran.', phone: '1-844-363-1423' } } }, community: { title: 'Òganizasyon Kominotè', description: 'Sipò lokal pou imigran.', entries: { localCenters: { name: 'Sant Kominotè Lokal', description: 'Tcheke sant pou sèvis sipò.' }, religiousOrgs: { name: 'Òganizasyon Relijye', description: 'Legliz ak mosk ofri sipò.' }, legalAidSocieties: { name: 'Sosyete Èd Legal', description: 'Sèvis gratis oswa ti pri.' } } }, visitWebsite: 'Vizite Sit la →', playlistComingSoon: 'Lis videyo a byento.', noteTitle: 'Nòt', noteContent: 'Verifye enfòmasyon avan kontak.' },
    help: { title: 'Èd Papye', subtitle: 'Fòm Komen', description: 'Gid pou ranpli fòm yo.', commonFormsTitle: 'Fòm Komen', viewFormLabel: 'Gade →', tipsTitle: 'Konsèy', tips: { tip1: 'Li enstriksyon yo.', tip2: 'Lank nwa klè.', tip3: 'Reponn onètman.', tip4: 'Kenbe kopi yo.', tip5: 'Konsilte avoka si bezwen.', tip6: 'Revize avan voye.' }, chatbotSectionTitle: 'Bezwen èd?', chatbotSectionDescription: 'Itilize chatbot la.', disclaimerText: 'Toujou verifye sous ofisyèl yo.' },
    about: { title: 'Konsènan Immigo', subtitle: 'Bay pouvwa ak enfòmasyon', description: 'Ede imigran konprann dwa yo.', missionTitle: 'Misyon Nou', whatWeOfferTitle: 'Sa Nou Ofri', features: { rightsLabel: 'Konnen Dwa Ou', resourceFinderLabel: 'Rechèch Resous', paperworkHelpLabel: 'Èd Papye', aiAssistantLabel: 'Asistan IA', multilingualSupportLabel: 'Sipò Plizyelang' }, disclaimerTitle: 'Avi Legal', contactTitle: 'Kontak', disclaimerText: 'Enfòmasyon sèlman – pa konsèy legal.', contactText: 'Kontakte nou atravè chatbot la.' },
    chatbot: { title: 'Asistan IA', placeholder: 'Poze yon kesyon...', send: 'Voye', thinking: 'Ap panse...', error: 'Gen yon erè.', apiKeyMissing: 'Mete VITE_GEMINI_API_KEY.', welcomeGreeting: '👋 Asistan IA', welcomePrompt: 'Poze kesyon sou dwa/resous.', toggleAria: 'Chanje chatbot', closeAria: 'Fèmen chatbot', systemPrompt: 'Bay enfòmasyon sou imigrasyon. Pa konsèy legal.' },
    footer: { description: 'Bay imigran konesans.', rights: 'Tout dwa rezève.' }
  } }
};

i18n.use(LanguageDetector).use(initReactI18next).init({
  resources,
  fallbackLng: 'en',
  interpolation: { escapeValue: false }
});

export default i18n;

